### ISSUE TITLE
License

### ISSUE THREAD

**Issue by damiendr** [Jakobovski/free-spoken-digit-dataset#3]
Have you considered choosing a license (Creative Commons for instance) to make explicit the conditions for copying and reuse?

**Comment by cesarsouza** [comment]
Hi @Jakobovski,

I am also willing to help expanding this dataset, but can you please first let us know what are the license restrictions of your original recordings (and of this repository in general)? 

Please consider a [Creative Commons Attribution Share-Alike](https://creativecommons.org/licenses/by-sa/4.0/legalcode) license in order to draw attention of both individual developers and companies towards your dataset.

Regards,
Cesar

**Comment by Jakobovski** [comment]
Done. Thanks!
